### ISSUE TITLE
Always response: Error: invalid argument(s) . when call sendRawTranscation on nodejs side

### ISSUE THREAD

**Issue by flyonce** [nebulasio/neb.js#36]
Hey
   when i try to send transaction by api 'sendRawTransaction' on nodejs side, it always result in error like below:
```
Error: invalid argument(s)
    at /Users/jazz/Desktop/个人/NAS钱包/proj/nodeserver/node_modules/nebulas/lib/httprequest.js:48:19
    at <anonymous>
    at process._tickCallback `(internal/process/next_tick.js:188:7)
```
may anyone has ideals,  i test it on testnet: https://testnet.nebulas.io/  and my code is: 
```
var callContract = function(params) {
    neb.api.getAccountState(params.from).then(function (resp) {
        params.nonce = parseInt(resp.nonce) + 1;
        var gTx = new nebulas.Transaction(globalParams.chainId,
        globalParams.account,params.to, params.value, params.nonce, params.gasPrice, params.gasLimit, params.contract);

        console.log(gTx);

        gTx.signTransaction();

        console.log(gTx);

        neb.api.sendRawTransaction(gTx.toProtoString()).then(function (resp) {
            console.log(JSON.stringify(resp));
        })
        .catch(function (err) {
            console.log(err);
        });
    });
};
```

**Comment by yupnano** [comment]
it should be the problem of your `params`. Please show more information about it.

**Comment by ChengOrangeJu** [comment]
Issue closed for now. If there still pending issues, please reopen this ticket, thanks @flyonce
