### ISSUE TITLE
为什么不能像nebPay一样，编译完同时生成一个nebulas.min.js压缩文件

### ISSUE THREAD

**Issue by GreatBareBear** [nebulasio/neb.js#56]
nebulas.js本身要1M多，为什么编译时不提供生成一个nebulas.min.js压缩文件呢?

**Comment by GreatBareBear** [comment]
GulpUglifyError: unable to minify JavaScript
    at createError (G:\Dapp\neb.js\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at apply (G:\Dapp\neb.js\node_modules\gulp-uglify\node_modules\lodash\_apply.js:16:25)
    at wrapper (G:\Dapp\neb.js\node_modules\gulp-uglify\node_modules\lodash\_createCurry.js:41:12)
    at G:\Dapp\neb.js\node_modules\gulp-uglify\lib\minify.js:54:15
    at DestroyableTransform._transform (G:\Dapp\neb.js\node_modules\gulp-uglify\composer.js:10:23)
    at DestroyableTransform.Transform._read (G:\Dapp\neb.js\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (G:\Dapp\neb.js\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (G:\Dapp\neb.js\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (G:\Dapp\neb.js\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (G:\Dapp\neb.js\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Transform.ondata (G:\Dapp\neb.js\node_modules\gulp-streamify\node_modules\readable-stream\lib\_stream_readable.js:572:20)
    at emitOne (events.js:116:13)
    at Transform.emit (events.js:211:7)
    at readableAddChunk (G:\Dapp\neb.js\node_modules\gulp-streamify\node_modules\readable-stream\lib\_stream_readable.js:195:16)
    at Transform.Readable.push (G:\Dapp\neb.js\node_modules\gulp-streamify\node_modules\readable-stream\lib\_stream_readable.js:162:10)
    at Transform.push (G:\Dapp\neb.js\node_modules\gulp-streamify\node_modules\readable-stream\lib\_stream_transform.js:145:32)

自己压缩还报错，压缩不了

**Comment by 1c7** [comment]
为什么自己 close 了这个问题？有后续吗？你压缩成功了吗？
我在 mac 上显示 nebulas.js 有 1.2m，太大了。
![image](https://user-images.githubusercontent.com/1804755/44321264-8ee26580-a479-11e8-828a-7e232dca1b7d.png)
